# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.2
loader_version=0.19.1
# Mod Properties
mod_version=1.0+mc26.1.2
maven_group=koi.pond
archives_base_name=DisableHotbarWrap
# Dependencies
# check this on https://modmuss50.me/fabric.html
# fabric_api_version=0.144.0+26.1
# Note if using fabric api: In fabric.mod.json, below line 23, add "fabric-api": "*",
loom_version=1.16.1
